#ifndef __IBUTTERFREE_LOG_H__
#define __IBUTTERFREE_LOG_H__

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <stdarg.h>

#define ANSI_COLOR_RED     "\x1b[31m"
#define ANSI_COLOR_GREEN   "\x1b[32m"
#define ANSI_COLOR_BLUE    "\x1b[34m"
#define ANSI_COLOR_MAGENTA "\x1b[35m"
#define ANSI_COLOR_CYAN    "\x1b[36m"

#define PRINTFUNCTION(format, ...) printf(format, __VA_ARGS__)
#define NEWLINE "\n"

#define LOG_FMT			"[%s][%s - %s:%d]"
#define LOG_ARGS(LEVEL)	LEVEL, __FUNCTION__, __FILE__, __LINE__

#define	IBUTTERFREE_MSG_LEVEL_NONE	0
#define	IBUTTERFREE_MSG_LEVEL_TRACK	1
#define	IBUTTERFREE_MSG_LEVEL_DEBUG	2
#define	IBUTTERFREE_MSG_LEVEL_ALERT	3
#define	IBUTTERFREE_MSG_LEVEL_WRN	4
#define	IBUTTERFREE_MSG_LEVEL_ERROR	5
#define	IBUTTERFREE_MSG_LEVEL_ALL	6

#ifndef IBUTTERFREE_MSG_LEVEL
#define IBUTTERFREE_MSG_LEVEL IBUTTERFREE_MSG_LEVEL_NONE
#endif

#if IBUTTERFREE_MSG_LEVEL >= IBUTTERFREE_MSG_LEVEL_TRACK
#define IBUTTERFREE_LOG_TRACK(message, args...) \
	PRINTFUNCTION(ANSI_COLOR_CYAN LOG_FMT message ANSI_COLOR_CYAN NEWLINE, LOG_ARGS("TRACK"), ## args)
#else 
#define	IBUTTERFREE_LOG_TRACK(message, args...)		
#endif

#if IBUTTERFREE_MSG_LEVEL >= IBUTTERFREE_MSG_LEVEL_DEBUG
#define IBUTTERFREE_LOG_DEBUG(message, args...) \
	PRINTFUNCTION(ANSI_COLOR_BLUE LOG_FMT message ANSI_COLOR_BLUE NEWLINE, LOG_ARGS("DEBUG"), ## args)
#else 
#define IBUTTERFREE_LOG_DEBUG(message, args...)	
#endif

#if IBUTTERFREE_MSG_LEVEL >= IBUTTERFREE_MSG_LEVEL_ALERT
#define IBUTTERFREE_LOG_ALERT(message, args...) \
	PRINTFUNCTION(ANSI_COLOR_GREEN LOG_FMT message ANSI_COLOR_GREEN NEWLINE, LOG_ARGS("ALERT"), ## args)
#else 
#define	IBUTTERFREE_LOG_ALERT(message, args...)	
#endif

#if IBUTTERFREE_MSG_LEVEL >= IBUTTERFREE_MSG_LEVEL_WARNING
#define IBUTTERFREE_LOG_WARNING(message, args...) \
	PRINTFUNCTION(ANSI_COLOR_MAGENTA LOG_FMT message ANSI_COLOR_MAGENTA NEWLINE, LOG_ARGS("WARNING"), ## args)
#else 
#define IBUTTERFREE_LOG_WARNING(message, args...)	
#endif

#if (IBUTTERFREE_MSG_LEVEL >= IBUTTERFREE_MSG_LEVEL_ERROR)
#define IBUTTERFREE_LOG_ERROR(message, args...) \
	PRINTFUNCTION(ANSI_COLOR_RED LOG_FMT message ANSI_COLOR_RED NEWLINE, LOG_ARGS("ERROR"), ## args)
#else 
#define	IBUTTERFREE_LOG_ERROR(message, args...)	
#endif	

#endif